### ISSUE TITLE
unresolved dependencies 

### ISSUE THREAD

**Issue by simonezando** [akileev/akka-serial-io#1]
Hi Artem,

I have a problem with import library in my Play project with:

 libraryDependencies += "com.github.akileev" %% "akka-serial-io" % "1.0.0"   

The problem which show me in console is:

[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.akileev#akka-serial-io_2.11;1.0.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

I have all requirements (Java 1.8, Akka 2.4.1)
Can you help me?

Thanks for support.

**Comment by akileev** [comment]
Sonatype repository does not ready yet.

**Comment by akileev** [comment]
Repository is ready to use.
